Move default settings definition to function `default_settings()`
plone/guillotina_elasticsearch pull request #69
Opened 2020-03-19 16:42 UTC by masipcat

2020-03-20 08:02 UTC, lferran approved these changes

2020-03-20 22:18 UTC, bloodbare requested changes
How we can extend on a third party package, like adding analyzers?

2020-03-21 10:51 UTC, masipcat commented
guillotina_elasticsearch reads the settings from `app_settings['elasticsearch']` and uses `default_settings()` as a fallback:
https://github.com/plone/guillotina_elasticsearch/blob/9ea419449c7cb2087940b6636860963310c869bd/guillotina_elasticsearch/manager.py#L67-L72

In case you want to add/modify analyzers you can do it like this:
```python
# in __init__.py

app_settings = {
    ....
    "elasticsearch": mergedict(default_settings(), {"analyzers": ...})
}
```
or if you want to overwrite the entire configuration:
```python
app_settings = {
    "elasticsearch": {"analyzers": ...}
}
```

2020-03-21 10:53 UTC, masipcat commented
The actual problem is that I'm customizing `app_settings["elasticsearch"]` in my application and when `manager.py` tries to read `app_settings["elasticsearch"]["default_settings"]` doesn't exist.

2020-03-24 15:14 UTC, vangheem approved these changes

2020-03-25 14:57 UTC, bloodbare approved these changes

2020-03-25 15:02 UTC, merged